[project]
name = "soundsnatch"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "altgraph==0.17.4",
    "packaging==25.0",
    "pyinstaller==6.14.1",
    "pyinstaller-hooks-contrib==2025.5",
    "yt-dlp==2025.6.9",
]
